Feat/381-shared-be-add-signupstaker-api
SwellNetwork/shared pull request #12
Opened 2022-07-29 12:36 UTC by daisai3

- task: https://trello.com/c/DChqVruS/381-shared-be-add-signupstaker-api

2022-07-29 12:37 UTC, aaron-alderman approved these changes

2022-07-30 10:31 UTC, leckylao approved these changes

2022-07-30 10:33 UTC, leckylao requested changes
I remember we were deleting the index.js before as no use? Is it still the case?

2022-07-30 11:10 UTC, leckylao approved these changes

2022-07-30 11:22 UTC, merged