feat: [BE] Add API key for our GraphQL query
SwellNetwork/shared pull request #19
Opened 2022-08-03 14:37 UTC by KevinChristopher1014

https://trello.com/c/x7lgro0I/369-be-add-api-key-for-our-graphql-query

2022-08-03 15:13 UTC, aaron-alderman reviewed
Call it `apiKey` instead of `api`

2022-08-04 11:23 UTC, aaron-alderman approved these changes

2022-08-05 07:11 UTC, leckylao requested changes
Need to add name for the migration folder rather than date

2022-08-05 23:37 UTC, leckylao approved these changes

2022-08-06 05:47 UTC, merged