Feat/422-shared-be-add-a-new-query-to-check-if-referral-code-is-valid
SwellNetwork/shared pull request #21
Opened 2022-08-05 13:50 UTC by daisai3

- task: https://trello.com/c/daKBFHE6/422-shared-be-add-a-new-query-to-check-if-referral-code-is-valid

2022-08-05 14:14 UTC, leckylao requested changes
I will need to review all other PR together, Otherwise I have no idea for the `isTakenReferalCode `

2022-08-06 00:31 UTC, leckylao approved these changes

2022-08-07 13:32 UTC, super1114 approved these changes

2022-08-08 09:30 UTC, aaron-alderman approved these changes

2022-08-08 11:42 UTC, merged