Feat/432-shared-setup-eslint-and-prettier-configuration-to-be-synced-on-be-repo
SwellNetwork/shared pull request #25
Opened 2022-08-07 12:57 UTC by daisai3

- task: https://trello.com/c/93vFCbcG/432-shared-setup-eslint-and-prettier-configuration-to-be-synced-on-be-repo

2022-08-07 14:00 UTC, leckylao requested changes
Also add husky so that it can auto run on staging file

2022-08-07 16:51 UTC, aaron-alderman approved these changes

2022-08-08 00:01 UTC, daisai3 commented
> Also add husky so that it can auto run on staging file

Okay

2022-08-08 12:32 UTC, daisai3 commented
> 

@leckylao husky setup is done.

2022-08-08 12:41 UTC, leckylao approved these changes

2022-08-08 12:42 UTC, merged