feat: add ApiStats model
SwellNetwork/shared pull request #32
Opened 2022-08-11 13:57 UTC by KevinChristopher1014

https://trello.com/c/VUSYki9M/435-api-track-api-usage

2022-08-11 14:07 UTC, KevinChristopher1014 commented
https://github.com/SwellNetwork/backend/pull/205

2022-08-11 14:12 UTC, aaron-alderman approved these changes

2022-08-12 00:36 UTC, daisai3 requested changes

2022-08-12 00:36 UTC, daisai3 commented on prisma/schema.prisma
> +  ApiStats     ApiStats[]
I reckon to use lowerCase. `apiStatus`. Need to confirm with Lecky and Aaron

2022-08-12 00:36 UTC, daisai3 commented on prisma/schema.prisma
> +  URL          String        @db.VarChar(255)
I reckon to use lowercase field. - `url`. Need to confirm with @leckylao and @aaron-alderman .

2022-08-14 07:51 UTC, leckylao commented on prisma/schema.prisma
> +  ApiStats     ApiStats[]
Agreed

2022-08-14 07:51 UTC, leckylao commented on prisma/schema.prisma
> +  URL          String        @db.VarChar(255)
Agreed

2022-08-16 13:22 UTC, leckylao requested changes

2022-08-16 13:22 UTC, leckylao commented on prisma/migrations/20220814140853_add_api_stats_model/migration.sql
> +    "totalUsed" INTEGER NOT NULL,
Add userApiKey which should act as foreign key from users.apiKey

2022-08-16 13:22 UTC, leckylao commented on prisma/schema.prisma
> +  totalUsed    Int
Also add unique constraint for [url, userId, userApiKey]

2022-08-17 14:45 UTC, aaron-alderman submitted a review, later dismissed

2022-08-23 06:04 UTC, leckylao requested changes

2022-08-23 06:04 UTC, leckylao commented on prisma/schema.prisma
> +  userId       Int
I am thinking replace userId with userApiKey, so that the user relation would be fields userAPiKey and reference userApiKey. That way we could look up user with userApiKey which is unique on users table

2022-08-23 13:58 UTC, closed without merging