feat: 520-beshared-add-getuserbyreferalcode-query-api
SwellNetwork/shared pull request #39
Opened 2022-08-23 09:52 UTC by daisai3

- task: https://trello.com/c/yvvczEee/520-beshared-add-getuserbyreferalcode-query-api

2022-08-23 10:22 UTC, aaron-alderman requested changes
Change to GetUserByReferralCodes and return array of items

2022-08-23 13:39 UTC, daisai3 commented
> Change to GetUserByReferralCodes and return array of items

It was renamed to GetUserByReferralCodes.

2022-08-24 03:55 UTC, aaron-alderman requested changes

2022-08-24 03:55 UTC, aaron-alderman commented on graphql/getUserByReferralCodes.ts
> +const GET_USER_BY_REFERRAL_CODES = gql(`
Will need plural to keep consistent
`GET_USERS_BY_REFERRAL_CODES`
`GetUsersByReferralCodes`
`getUsersByReferralCodes`

2022-08-24 10:11 UTC, daisai3 commented on graphql/getUserByReferralCodes.ts
> +const GET_USER_BY_REFERRAL_CODES = gql(`
Fixed it

2022-08-24 14:28 UTC, leckylao approved these changes

2022-08-24 14:33 UTC, aaron-alderman approved these changes

2022-08-24 17:15 UTC, merged