feat: add ApiStats model for track API usage
SwellNetwork/shared pull request #40
Opened 2022-08-23 13:57 UTC by KevinChristopher1014

2022-08-23 13:58 UTC, KevinChristopher1014 commented
Closed https://github.com/SwellNetwork/shared/pull/32

2022-08-23 14:07 UTC, aaron-alderman approved these changes

2022-08-24 13:57 UTC, leckylao requested changes

2022-08-24 13:57 UTC, leckylao commented on prisma/schema.prisma
> +  totalUsed    Int
I think you can put @default(autoincrement()), same as id, then you don't need to set this value

2022-08-30 13:04 UTC, KevinChristopher1014 commented on prisma/schema.prisma
> +  totalUsed    Int
@leckylao 
I think we can't use autoincrement()
Because it doesn't update totalUsed value when update record.
If we use totalUsed, it will be same as id.

2022-09-01 06:18 UTC, leckylao approved these changes

2022-09-01 13:42 UTC, aaron-alderman approved these changes

2022-09-01 14:28 UTC, merged