feat: get apiKey when create user
SwellNetwork/shared pull request #42
Opened 2022-08-31 15:30 UTC by KevinChristopher1014

https://trello.com/c/x7lgro0I/369-be-add-api-key-for-our-graphql-query

2022-08-31 15:55 UTC, aaron-alderman requested changes

2022-08-31 15:55 UTC, aaron-alderman commented on graphql/createOrUpdateUser.ts
> +  mutation CreateOrUpdateUser($createOrUpdateUserInput: CreateOrUpdateUserInput!, $userSignatureInput: UserSignatureInput!) {
Intentional?
This would need to be updated in schema.graphql and schema.ts on backend

2022-08-31 15:58 UTC, KevinChristopher1014 commented on graphql/createOrUpdateUser.ts
> +  mutation CreateOrUpdateUser($createOrUpdateUserInput: CreateOrUpdateUserInput!, $userSignatureInput: UserSignatureInput!) {
yes. @aaron-alderman 
the first letter of  all operation names are uppercase.
so I changed.

2022-09-01 06:37 UTC, leckylao approved these changes

2022-09-01 13:41 UTC, aaron-alderman approved these changes

2022-09-01 14:29 UTC, merged